export const CHANGE_CURRENT_SONG = "player/CHANGE_CURRENT_SONG"
export const CHANGE_CURRENT_PLAYLIST = "player/CHANGE_CURRENT_PLAYLIST"
export const CHANGE_CURRENT_SONG_INDEX = "player/CHANGE_CURRENT_SONG_INDEX"

export const CHANGE_SEQUENCE = "player/CHANGE_SEQUENCE"
export const CHANGE_LYRIC = "player/CHANGE_LYRIC"